name: Website Recommendation
description: Recommend a Website that should be added to the Blocklist
title: "Website Recommendation"
labels: "Website"
body:
- type: input
  id: Website-input
  attributes:
    label: Website to Block
    description: "What Website do you want Blocked?"
    placeholder: "Website URL"
  validations:
    required: true

- type: textarea
  id: Why-Should-website-be-blocked
  attributes:
    label: Why Should this be Blocked?
    description: "Why Should this Website Be Blocked?"
    render: bash
  validations:
    required: true

- type: dropdown
  id: what-kind-of-website-is-it
  attributes:
    label: What Kind of Content does it contain?
    options:
    - Inappropriate/Addictive Content
    - Gambling
    - Cam Website
    - Nudity
    - Dating
    - Other...
  validations:
    required: true

- type: input
  id: the_option_for_dropdown
  attributes:
    label: "Describe the other issue"
    description: "Please describe the issue you are experiencing."
    placeholder: "Describe your issue here"
    render: false
    depends_on:
      - id: what-kind-of-website-is-it
        value: "Other..."
