name: Website reccomendation
description: Reccomend a Website that should be added to the Blocklist
title: "[Website]: "
labels: "Website"
body:
- type: input
  id: Website-input
  attributes:
    label: Website to Block
    description: "What Website do you want Blocked?"
    placeholder: "Website URL"
  validations:
    required: true
